<?php
require_once 'auth.php';
require_once 'vendor/autoload.php';

if (!isUserLoggedIn()) {
    header('Location: login.php');
    exit;
}

use Dompdf\Dompdf;
use Dompdf\Options;

$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $reportType = $_POST['report_type'] ?? '';
        $dateFrom = $_POST['date_from'] ?? '';
        $dateTo = $_POST['date_to'] ?? '';
        $userId = $_SESSION['user_id'] ?? 0;

        if (empty($reportType)) {
            throw new Exception('Please select a report type');
        }

        // Set default date range if not provided
        if (empty($dateFrom))
            $dateFrom = date('Y-m-01'); // First day of current month
        if (empty($dateTo))
            $dateTo = date('Y-m-d'); // Today

        $reportData = [];
        $reportTitle = '';

        switch ($reportType) {
            case 'projects':
                $stmt = $pdo->prepare("SELECT * FROM projects WHERE created_at BETWEEN ? AND ? ORDER BY created_at DESC");
                $stmt->execute([$dateFrom, $dateTo]);
                $reportData = $stmt->fetchAll(PDO::FETCH_ASSOC);
                $reportTitle = 'Projects Report';
                break;

            case 'messages':
                $stmt = $pdo->prepare("SELECT * FROM messages WHERE created_at BETWEEN ? AND ? ORDER BY created_at DESC");
                $stmt->execute([$dateFrom, $dateTo]);
                $reportData = $stmt->fetchAll(PDO::FETCH_ASSOC);
                $reportTitle = 'Messages Report';
                break;

            case 'users':
                if (!isAdmin()) {
                    throw new Exception('Access denied: Admin privileges required for user reports');
                }
                $stmt = $pdo->prepare("SELECT id, username, email, created_at, is_admin FROM users WHERE created_at BETWEEN ? AND ? ORDER BY created_at DESC");
                $stmt->execute([$dateFrom, $dateTo]);
                $reportData = $stmt->fetchAll(PDO::FETCH_ASSOC);
                $reportTitle = 'Users Report';
                break;

            case 'my_imports':
                $stmt = $pdo->prepare("SELECT * FROM excel_imports WHERE imported_by = ? AND imported_at BETWEEN ? AND ? ORDER BY imported_at DESC");
                $stmt->execute([$userId, $dateFrom, $dateTo]);
                $reportData = $stmt->fetchAll(PDO::FETCH_ASSOC);
                $reportTitle = 'My Data Imports Report';
                break;

            default:
                throw new Exception('Invalid report type');
        }

        // Generate PDF
        $options = new Options();
        $options->set('defaultFont', 'Arial');
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);

        $html = generateReportHTML($reportTitle, $reportData, $dateFrom, $dateTo, $reportType);

        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $filename = strtolower(str_replace(' ', '_', $reportTitle)) . '_' . date('Y-m-d_H-i-s') . '.pdf';

        // Save report record
        $stmt = $pdo->prepare("INSERT INTO pdf_reports (report_type, filename, created_by, date_from, date_to) VALUES (?, ?, ?, ?, ?)");
        $stmt->execute([$reportType, $filename, $userId, $dateFrom, $dateTo]);

        // Output PDF
        $dompdf->stream($filename, array('Attachment' => true));
        exit;

    } catch (Exception $e) {
        $error = $e->getMessage();
    }
}

function generateReportHTML($title, $data, $dateFrom, $dateTo, $reportType)
{
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #007bff; padding-bottom: 20px; }
            .info { background: #f8f9fa; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #007bff; color: white; }
            tr:nth-child(even) { background-color: #f2f2f2; }
            .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>' . htmlspecialchars($title) . '</h1>
            <p>Generated on ' . date('Y-m-d H:i:s') . '</p>
        </div>
        
        <div class="info">
            <strong>Report Period:</strong> ' . htmlspecialchars($dateFrom) . ' to ' . htmlspecialchars($dateTo) . '<br>
            <strong>Total Records:</strong> ' . count($data) . '<br>
            <strong>Generated by:</strong> ' . htmlspecialchars($_SESSION['username']) . '
        </div>';

    if (empty($data)) {
        $html .= '<p>No data found for the selected period.</p>';
    } else {
        $html .= '<table>';

        // Table headers based on report type
        switch ($reportType) {
            case 'projects':
                $html .= '<tr><th>ID</th><th>Title</th><th>Description</th><th>Status</th><th>Created At</th></tr>';
                foreach ($data as $row) {
                    $html .= '<tr>
                        <td>' . htmlspecialchars($row['id']) . '</td>
                        <td>' . htmlspecialchars($row['title'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars(substr($row['description'] ?? '', 0, 100)) . '...</td>
                        <td>' . htmlspecialchars($row['status'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($row['created_at']) . '</td>
                    </tr>';
                }
                break;

            case 'messages':
                $html .= '<tr><th>ID</th><th>Name</th><th>Email</th><th>Subject</th><th>Created At</th></tr>';
                foreach ($data as $row) {
                    $html .= '<tr>
                        <td>' . htmlspecialchars($row['id']) . '</td>
                        <td>' . htmlspecialchars($row['name'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($row['email'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($row['subject'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($row['created_at']) . '</td>
                    </tr>';
                }
                break;

            case 'users':
                $html .= '<tr><th>ID</th><th>Username</th><th>Email</th><th>Role</th><th>Created At</th></tr>';
                foreach ($data as $row) {
                    $html .= '<tr>
                        <td>' . htmlspecialchars($row['id']) . '</td>
                        <td>' . htmlspecialchars($row['username']) . '</td>
                        <td>' . htmlspecialchars($row['email']) . '</td>
                        <td>' . ($row['is_admin'] ? 'Admin' : 'User') . '</td>
                        <td>' . htmlspecialchars($row['created_at']) . '</td>
                    </tr>';
                }
                break;

            case 'my_imports':
                $html .= '<tr><th>ID</th><th>Filename</th><th>Records</th><th>Status</th><th>Imported At</th></tr>';
                foreach ($data as $row) {
                    $html .= '<tr>
                        <td>' . htmlspecialchars($row['id']) . '</td>
                        <td>' . htmlspecialchars($row['filename']) . '</td>
                        <td>' . htmlspecialchars($row['total_records']) . '</td>
                        <td>' . htmlspecialchars($row['status']) . '</td>
                        <td>' . htmlspecialchars($row['imported_at']) . '</td>
                    </tr>';
                }
                break;
        }

        $html .= '</table>';
    }

    $html .= '
        <div class="footer">
            <p>Portfolio Email System - Report Generated Automatically</p>
        </div>
    </body>
    </html>';

    return $html;
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Reports - Portfolio Email System</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #28a745;
            padding-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        select,
        input[type="date"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 16px;
        }

        .btn {
            background: #28a745;
            color: white;
            padding: 12px 30px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            margin-right: 10px;
        }

        .btn:hover {
            background: #1e7e34;
        }

        .btn-secondary {
            background: #6c757d;
        }

        .btn-secondary:hover {
            background: #545b62;
        }

        .alert {
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
        }

        .alert-success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .alert-danger {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        .date-range {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
        }

        .report-info {
            background: #e9ecef;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>📊 Generate PDF Reports</h1>
            <p>Create detailed reports from your portfolio data</p>
        </div>

        <?php if ($message): ?>
            <div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div>
        <?php endif; ?>

        <?php if ($error): ?>
            <div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div>
        <?php endif; ?>

        <div class="report-info">
            <strong>Available Report Types:</strong><br>
            • <strong>Projects:</strong> All projects in your portfolio<br>
            • <strong>Messages:</strong> Contact form messages received<br>
            • <strong>My Imports:</strong> Your Excel data import history<br>
            <?php if (isAdmin()): ?>
                • <strong>Users:</strong> System user accounts (Admin only)<br>
            <?php endif; ?>
        </div>

        <form method="POST">
            <div class="form-group">
                <label for="report_type">Report Type:</label>
                <select name="report_type" id="report_type" required>
                    <option value="">Select Report Type</option>
                    <option value="projects">Projects Report</option>
                    <option value="messages">Messages Report</option>
                    <option value="my_imports">My Data Imports</option>
                    <?php if (isAdmin()): ?>
                        <option value="users">Users Report (Admin)</option>
                    <?php endif; ?>
                </select>
            </div>

            <div class="form-group">
                <label>Date Range:</label>
                <div class="date-range">
                    <div>
                        <label for="date_from">From:</label>
                        <input type="date" name="date_from" id="date_from" value="<?php echo date('Y-m-01'); ?>">
                    </div>
                    <div>
                        <label for="date_to">To:</label>
                        <input type="date" name="date_to" id="date_to" value="<?php echo date('Y-m-d'); ?>">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn">📊 Generate PDF Report</button>
                <a href="user_dashboard.php" class="btn btn-secondary">← Back to Dashboard</a>
            </div>
        </form>
    </div>
</body>

</html>